name: Build and Push Docker Images

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
      options: --privileged --add-host=gitea:192.168.1.70 -v /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Docker
        run: docker info

      - name: Login to Gitea Registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login 192.168.1.70:3000 -u janbndrf --password-stdin

      - name: Build backend
        run: docker build -f Dockerfile.backend -t 192.168.1.70:3000/janbndrf/tabtin-backend:latest -t 192.168.1.70:3000/janbndrf/tabtin-backend:${{ github.sha }} .

      - name: Build frontend
        run: docker build -f Dockerfile.frontend -t 192.168.1.70:3000/janbndrf/tabtin-frontend:latest -t 192.168.1.70:3000/janbndrf/tabtin-frontend:${{ github.sha }} .

      - name: Push backend
        run: |
          docker push 192.168.1.70:3000/janbndrf/tabtin-backend:latest
          docker push 192.168.1.70:3000/janbndrf/tabtin-backend:${{ github.sha }}

      - name: Push frontend
        run: |
          docker push 192.168.1.70:3000/janbndrf/tabtin-frontend:latest
          docker push 192.168.1.70:3000/janbndrf/tabtin-frontend:${{ github.sha }}
