name: Build and Push Docker Images

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
      options: --privileged --add-host=gitea:192.168.1.70
    services:
      docker:
        image: docker:24-dind
        options: --privileged
        env:
          DOCKER_TLS_CERTDIR: ""
    env:
      DOCKER_HOST: tcp://docker:2375
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait for Docker
        run: |
          for i in $(seq 1 30); do
            docker info && break || sleep 2
          done

      - name: Login to Gitea Registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login 192.168.1.70:3000 -u janbndrf --password-stdin

      - name: Build backend
        run: docker build -f Dockerfile.backend -t 192.168.1.70:3000/janbndrf/tabtin-backend:latest -t 192.168.1.70:3000/janbndrf/tabtin-backend:${{ github.sha }} .

      - name: Build frontend
        run: docker build -f Dockerfile.frontend -t 192.168.1.70:3000/janbndrf/tabtin-frontend:latest -t 192.168.1.70:3000/janbndrf/tabtin-frontend:${{ github.sha }} .

      - name: Push backend
        run: |
          docker push 192.168.1.70:3000/janbndrf/tabtin-backend:latest
          docker push 192.168.1.70:3000/janbndrf/tabtin-backend:${{ github.sha }}

      - name: Push frontend
        run: |
          docker push 192.168.1.70:3000/janbndrf/tabtin-frontend:latest
          docker push 192.168.1.70:3000/janbndrf/tabtin-frontend:${{ github.sha }}
