name: Build and Push Docker Images

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Gitea Registry
        uses: docker/login-action@v3
        with:
          registry: 192.168.1.70:3000
          username: janbndrf
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: |
            192.168.1.70:3000/janbndrf/tabtin-backend:latest
            192.168.1.70:3000/janbndrf/tabtin-backend:${{ github.sha }}
          network: host

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.frontend
          push: true
          tags: |
            192.168.1.70:3000/janbndrf/tabtin-frontend:latest
            192.168.1.70:3000/janbndrf/tabtin-frontend:${{ github.sha }}
          network: host
